# Generated by Django 3.0.7 on 2020-11-12 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created',
        ),
        migrations.AddField(
            model_name='note',
            name='date_added',
            field=models.DateField(default=datetime.date(2020, 11, 12)),
        ),
    ]
