# Generated by Django 3.0.7 on 2020-11-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_notes', '0002_auto_20201112_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_added',
            field=models.DateField(default='13-11-2020'),
        ),
    ]
